### ISSUE TITLE
Consider adding ai2svelte ai template with the right settings

### ISSUE THREAD

**Issue by MinamiFunakoshiTR** [reuters-graphics/bluprint_graphics-kit#32]
Especially if Sam Granados and others who use ai a lot are going to use the new rig

**Comment by hobbes7878** [comment]
For now, early adopters will have to copy the settings from the [docs](https://github.com/reuters-graphics/bluprint_graphics-kit/blob/master/docs/developers/ai.md#adobe-illustrator-graphics), since we only have/want one template across both rigs, BUT as soon as we have critical mass ... mostly waiting on adopters in APAC, we'll finally flip that, and folks working in the old rig will need to adjust settings, instead.

Only a matter of time :)
